/** @deprecated Usar `@/lib/brand`. Re-export temporal para imports legacy. */
export {
  BRAND_ADDRESS_DETAIL as EPICA_ADDRESS_DETAIL,
  BRAND_ADDRESS_LINE as EPICA_ADDRESS_LINE,
  BRAND_MAPS_EMBED_SRC as EPICA_ADDRESS_MAPS_EMBED_URL,
  BRAND_MAPS_SHARE_URL as EPICA_ADDRESS_MAPS_SEARCH_URL,
  BRAND_HOME_INTRO as EPICA_HOME_INTRO,
  BRAND_INSTAGRAM_HANDLE as EPICA_INSTAGRAM_HANDLE,
  BRAND_INSTAGRAM_URL as EPICA_INSTAGRAM_URL,
  BRAND_LOGO_SRC as EPICA_LOGO_SRC,
  BRAND_HERO_IMAGE_SRC as EPICA_HERO_IMAGE_SRC,
  BRAND_NAME as EPICA_BRAND_NAME,
  BRAND_NAME_UPPER as EPICA_BRAND_NAME_UPPER,
  BRAND_SUBTITLE as EPICA_BRAND_SUBTITLE,
  BRAND_TAGLINE as EPICA_BRAND_TAGLINE,
  BRAND_WHATSAPP_DISPLAY as EPICA_WHATSAPP_DISPLAY,
  BRAND_WHATSAPP_URL as EPICA_WHATSAPP_URL,
  brandWhatsAppInquiryUrl as epicaWhatsAppInquiryUrl,
} from "@/lib/brand";
